name: Build

on:
  push

jobs:
  build-and-release:
    name: Build And Release
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          echo 'GOPROXY=direct' >>$GITHUB_ENV

      - name: Build
        run: |
          go vet ./...
          go test --cover ./...
